ImpactaDaniel/OPE-Restaurante

Restaurante.Application/Common/Models/EmailMessage.cs, Restaurante.Application/Users/Funcionarios/Requests/Create/CreateFuncionarioRequest.cs, Restaurante.Domain/Common/Models/Message.cs, Restaurante.Domain/Common/Services/Interfaces/IMessageSenderService.cs, Restaurante.Infra/Common/Services/SmtpEmailSenderService.cs, Restaurante.Infra/InfraConfiguration.cs, Restaurante.Test/Application/CreateFuncionarioRequestHandlerTest.cs, Restaurante.Test/Services/EmailServiceTest.cs
Enviando email com credenciais após cadastrar funcionário.
=> Enviando email com credenciais após cadastrar funcionário.

Restaurante.Application/ApplicationConfiguration.cs, Restaurante.Application/Common/Data/Mappers/EntregadorIntegrationMapper.cs, Restaurante.Application/Users/Entregadores/Services/EntregadorIntegrationService.cs, Restaurante.Application/Users/Entregadores/Services/EntregadorService.cs, Restaurante.Domain/Common/Data/Mappers/Interfaces/IMapper.cs, Restaurante.Domain/Common/Models/Integration/EntregadorIntegration.cs, Restaurante.Domain/Common/Models/Integration/IntegrationConfiguration.cs, Restaurante.Domain/Common/Models/Integration/IntegrationResponse.cs, Restaurante.Domain/Common/Services/Interfaces/IEntregadorIntegrationService.cs, Restaurante.Infra/Common/Persistence/DatabaseInitializer.cs, Restaurante.Test/Services/EntregadorServiceTest.cs, Restaurante.Test/Usuarios/Mocks/EntregadorIntegrationMock.cs, Restaurante.Web/ClientApp/src/app/cadastro-restaurante/cadastro-funcionario.component.ts
Começando serviço para integrar com cadastro de entregador.
=> Começando implementação do serviço para criar entregador.

Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Account.cs, Restaurante-Back-End/Restaurante.Web/Startup.cs, Restaurante-Front-End/src/app/pages/employee/create-employee/create-employee.component.ts, Restaurante-Front-End/src/app/services/consulta-cep.service.ts
Ajustando startup e separando serviço de consulta CEP.
=> Ajustando startup e separando serviço de consulta CEP.

.gitignore, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/Interfaces/IRestauranteDbContext.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/RestauranteDbContext.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20210922005831_adding-banks.Designer.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20210922005831_adding-banks.cs, Restaurante-Back-End/Restaurante.Web/Properties/launchSettings.json, Restaurante-Back-End/Restaurante.Web/Startup.cs, Restaurante-Back-End/Restaurante.sln, Restaurante-Front-End/.gitignore, Restaurante-Front-End/angular.json, Restaurante-Front-End/cypress.env.json, Restaurante-Front-End/cypress/integration/e2e/src/auth/auth.spec.js, Restaurante-Front-End/cypress/integration/e2e/src/employee/employee.spec.js, Restaurante-Front-End/cypress/support/commands.js, Restaurante-Front-End/package.json, Restaurante-Front-End/src/app/middlewares/TokenInterceptor.ts, Restaurante-Front-End/src/app/pages/employee/login-employee/login-employee.html, Restaurante-Front-End/src/app/pages/employee/login-employee/login-employee.ts, Restaurante-Front-End/src/app/services/alert.service.ts, Restaurante-Front-End/src/app/services/token.service.ts, Restaurante-Front-End/src/environments/environment.dev.ts, Restaurante-Front-End/src/environments/environment.prod.ts, Restaurante-Front-End/src/environments/environment.ts, Restaurante-Front-End/src/main.js, Restaurante-Front-End/src/main.ts
Implementando teste de autenticação.
=> Implementando teste de autenticação.

Restaurante-Back-End/Restaurante.Application/Common/Data/Mappers/DeliveryPersonIntegrationMapper.cs, Restaurante-Back-End/Restaurante.Application/Users/Common/Models/EmployeeRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Deliveries/Requests/Create/CreateDeliverymanRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Employees/Requests/Create/CreateEmployeeRequest.cs, Restaurante-Back-End/Restaurante.Domain/Common/Factories/DeliverFactory.cs, Restaurante-Back-End/Restaurante.Domain/Common/Factories/EmployeeFactory.cs, Restaurante-Back-End/Restaurante.Domain/Common/Factories/Interfaces/IDeliverFactory.cs, Restaurante-Back-End/Restaurante.Domain/Common/Factories/Interfaces/IEmployeeFactory.cs, Restaurante-Back-End/Restaurante.Domain/Common/Models/Entity.cs, Restaurante-Back-End/Restaurante.Domain/Users/Common/Models/User.cs, Restaurante-Back-End/Restaurante.Domain/Users/Delivers/Models/DeliveryPerson.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Account.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Address.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Bank.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Employee.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/Interfaces/IDbContext.cs, Restaurante-Back-End/Restaurante.Test/Application/CreateDeliverymanRequestHandlerTest.cs, Restaurante-Back-End/Restaurante.Test/Application/CreateFuncionarioRequestHandlerTest.cs, Restaurante-Back-End/Restaurante.Test/Application/Mappers/DeliveryPersonIntegrationMapperTest.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/AccountTest.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/AddressTest.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/BankTest.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/DeliveryPersonTest.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/EmployeeTest.cs, Restaurante-Back-End/Restaurante.Test/Services/FuncionarioRepositoryTest.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/EmployeeFactoryTest.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/EntregadorTest.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/FuncionarioTeste.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/Mocks/EmployeeMock.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/Mocks/EntregadorMock.cs
Implementando testes unitarios para o dominio.
=> Implementando testes unitarios para o dominio.

Restaurante-Back-End/Restaurante.Application/Users/Common/Requests/Auth/ChangePasswordFirstAccessRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Common/Services/TokenService.cs, Restaurante-Back-End/Restaurante.Application/Users/Deliveries/Services/DeliveryPersonService.cs, Restaurante-Back-End/Restaurante.Application/Users/Employees/Requests/Create/CreateEmployeeRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Employees/Services/EmployeeService.cs, Restaurante-Back-End/Restaurante.Domain/Common/Repositories/IDomainRepository.cs, Restaurante-Back-End/Restaurante.Domain/Users/Common/Models/TokenResponse.cs, Restaurante-Back-End/Restaurante.Domain/Users/Common/Models/User.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Services/Interfaces/IEmployeesService.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/DataRepository.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20210926234302_first-access.Designer.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20210926234302_first-access.cs, Restaurante-Back-End/Restaurante.Infra/Users/Employees/EmployeesRepository.cs, Restaurante-Back-End/Restaurante.Test/Application/Requests/ChangePasswordFirstAccessRequestHandlerTest.cs, Restaurante-Back-End/Restaurante.Web/Controllers/APIControllerBase.cs, Restaurante-Back-End/Restaurante.Web/Controllers/AuthController.cs, Restaurante-Back-End/Restaurante.Web/Controllers/EmployeesController.cs, Restaurante-Back-End/Restaurante.Web/Middlewares/RequestMiddleware.cs, Restaurante-Back-End/Restaurante.Web/Models/ChangePasswordModel.cs, Restaurante-Back-End/Restaurante.Web/Startup.cs
Serviço pra necessitar troca de senha no primeiro acesso.
=> Serviço pra necessitar troca de senha no primeiro acesso.

Restaurante-Back-End/Restaurante.Domain/Helpers/RegexHelpers.cs, Restaurante-Back-End/Restaurante.Domain/Helpers/ValidatorsHelper.cs, Restaurante-Back-End/Restaurante.Domain/Users/Common/Models/User.cs, Restaurante-Back-End/Restaurante.Infra/Users/Employees/EmployeesRepository.cs, Restaurante-Back-End/Restaurante.Test/Application/Requests/ChangePasswordFirstAccessRequestHandlerTest.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/EmployeeTest.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/EmployeeFactoryTest.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/EntregadorTest.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/Mocks/DataTest.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/Mocks/EmployeeMock.cs, Restaurante-Back-End/Restaurante.Test/Usuarios/Mocks/EntregadorMock.cs, Restaurante-Back-End/Restaurante.Web/Controllers/APIControllerBase.cs, Restaurante-Front-End/src/app/middlewares/GlobalErrorHandler.ts, Restaurante-Front-End/src/app/pages/employee/login-employee/login-employee.html
Implementando validação de senha
=> Implementando validação de senha

Restaurante-Back-End/Restaurante.Domain/Products/Models/Photo.cs, Restaurante-Back-End/Restaurante.Domain/Products/Models/Product.cs, Restaurante-Back-End/Restaurante.Domain/Products/Models/ProductCategory.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/Interfaces/IRestauranteDbContext.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/RestauranteDbContext.cs, Restaurante-Back-End/Restaurante.Infra/Mappings/EmployeeMapping.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211010030342_adding-product.Designer.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211010030342_adding-product.cs, Restaurante-Back-End/Restaurante.Infra/Restaurante.Infra.csproj, Restaurante-Back-End/Restaurante.Test/Domain/Entities/PhotoTests.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/ProductCategoryTests.cs, Restaurante-Back-End/Restaurante.Test/Domain/Entities/ProductTests.cs, Restaurante-Back-End/Restaurante.Web/.gitignore
Implementando testes do produto
=> Implementando testes do produto

Restaurante-Back-End/Restaurante.Application/BasicEntities/Requests/Banks/BankRequestsHandler.cs, Restaurante-Back-End/Restaurante.Application/BasicEntities/Requests/Common/BasicEntityRequests.cs, Restaurante-Back-End/Restaurante.Application/BasicEntities/Services/BasicEntitiesService.cs, Restaurante-Back-End/Restaurante.Application/Products/Requests/Delete/DeleteProductRequest.cs, Restaurante-Back-End/Restaurante.Domain/BasicEntities/Services/Interfaces/IBasicEntitiesService.cs, Restaurante-Back-End/Restaurante.Domain/Common/Data/Models/PaginationInfo.cs, Restaurante-Back-End/Restaurante.Domain/Common/Repositories/IDefaultDomainRepository.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/DefaultRepository.cs, Restaurante-Back-End/Restaurante.Web/Controllers/BanksController.cs, Restaurante-Front-End/src/app/pages/bank/bank.module.ts, Restaurante-Front-End/src/app/pages/bank/bank.routing.ts, Restaurante-Front-End/src/app/pages/bank/create/create.bank.module.ts, Restaurante-Front-End/src/app/pages/bank/list-bank/list-bank.component.html, Restaurante-Front-End/src/app/pages/bank/list-bank/list-bank.component.ts, Restaurante-Front-End/src/app/pages/bank/list-bank/list-bank.module.ts, Restaurante-Front-End/src/app/pages/employee/login-employee/login-employee.html, Restaurante-Front-End/src/app/pages/employee/login-employee/login-employee.ts, Restaurante-Front-End/src/app/services/entities/basicentities.service.ts
Finalizando listagem de bancos e definindo listagens padrão.
=> Finalizando listagem de bancos e definindo listagens padrão.

Restaurante-Back-End/Restaurante.Application/Invoices/Requests/Create/CreateInvoiceRequest.cs, Restaurante-Back-End/Restaurante.Application/Invoices/Requests/Update/UpdateInvoiceStatusRequest.cs, Restaurante-Back-End/Restaurante.Domain/Invoices/Models/Invoice.cs, Restaurante-Back-End/Restaurante.Domain/Invoices/Models/InvoiceLog.cs, Restaurante-Back-End/Restaurante.Infra/Invoices/Repositories/InvoiceRepository.cs, Restaurante-Back-End/Restaurante.Web/Startup.cs
Ajustando criação dos logs de pedido.
=> Ajustando criação dos logs de pedido.

Restaurante-Back-End/Restaurante.Web/Restaurante.Web.csproj, Restaurante-Back-End/Restaurante.Web/Startup.cs
=> Ajustando reference handler.

Restaurante-Back-End/Restaurante.Application/Invoices/Common/Models/Enums/InvoiceNotificationType.cs, Restaurante-Back-End/Restaurante.Application/Invoices/Requests/Create/CreateInvoiceRequest.cs, Restaurante-Back-End/Restaurante.Web/Startup.cs, Restaurante-Front-End/src/app/app.component.ts, Restaurante-Front-End/src/app/app.module.ts, Restaurante-Front-End/src/app/components/dialogs/new-invoice-dialog/new-invoice-dialog.component.css, Restaurante-Front-End/src/app/components/dialogs/new-invoice-dialog/new-invoice-dialog.component.html, Restaurante-Front-End/src/app/components/dialogs/new-invoice-dialog/new-invoice-dialog.component.ts, Restaurante-Front-End/src/app/components/dialogs/new-invoice-dialog/new-invoice-dialog.module.ts, Restaurante-Front-End/src/app/pages/bank/list-bank/list-bank.component.html, Restaurante-Front-End/src/app/pages/bank/list-bank/list-bank.component.scss, Restaurante-Front-End/src/app/pages/employee/create-employee/create-employee.component.html, Restaurante-Front-End/src/app/pages/invoice/services/invoice.service.ts
Implementando popup quando novo pedido é criado.
=> Implementando popup quando novo pedido é criado.

Restaurante-Back-End/Restaurante.Application/Invoices/Requests/Get/SearchInvoicesRequest.cs, Restaurante-Back-End/Restaurante.Application/Products/Requests/Get/GetAllProductsRequest.cs, Restaurante-Back-End/Restaurante.Application/Products/Requests/Get/SearchProductsRequest.cs, Restaurante-Back-End/Restaurante.Application/Products/Services/ProductService.cs, Restaurante-Back-End/Restaurante.Domain/Products/Repositories/Interfaces/IProductDomainRepository.cs, Restaurante-Back-End/Restaurante.Domain/Products/Services/Interfaces/IProductService.cs, Restaurante-Back-End/Restaurante.Infra/Products/ProductRepository.cs, Restaurante-Back-End/Restaurante.Test/Services/ProductServiceTests.cs, Restaurante-Back-End/Restaurante.Web/Controllers/InvoiceController.cs, Restaurante-Back-End/Restaurante.Web/Controllers/ProductsController.cs, Restaurante-Front-End/src/app/components/side-nav/side-nav.component.html, Restaurante-Front-End/src/app/components/side-nav/side-nav.component.ts, Restaurante-Front-End/src/app/pages/bank/create/create.component.ts, Restaurante-Front-End/src/app/pages/bank/list-bank/list-bank.component.ts, Restaurante-Front-End/src/app/pages/employee/create-employee/create-employee.component.ts, Restaurante-Front-End/src/app/pages/employee/login-employee/login-employee.ts, Restaurante-Front-End/src/app/pages/invoice/list-invoice/list-invoice.component.html, Restaurante-Front-End/src/app/pages/invoice/list-invoice/list-invoice.component.ts, Restaurante-Front-End/src/app/pages/invoice/services/invoice.service.ts, Restaurante-Front-End/src/app/pages/products/list-product/list-product.component.html, Restaurante-Front-End/src/app/pages/products/list-product/list-product.component.ts, Restaurante-Front-End/src/app/pages/products/list-product/list-product.module.ts, Restaurante-Front-End/src/app/pages/products/products.routing.ts, Restaurante-Front-End/src/app/pages/products/services/product.service.ts, Restaurante-Front-End/src/main.ts
Implementando lista de produtos, filtragem de pedidos dinamica.
=> Implementando lista de produtos, filtragem de pedidos dinamica.

Restaurante-Back-End/Restaurante.Application/Invoices/Requests/Get/SearchInvoicesRequest.cs, Restaurante-Front-End/src/app/pages/invoice/list-invoice/list-invoice.component.html, Restaurante-Front-End/src/app/pages/invoice/list-invoice/list-invoice.component.ts, Restaurante-Front-End/src/app/pages/invoice/services/invoice.service.ts
Implementação de filtros dinamicos para tela de pedidos.
=> Criado filtros dinamicos para tela de pedidos.

Restaurante-Back-End/Restaurante.Application/ApplicationConfiguration.cs, Restaurante-Back-End/Restaurante.Application/Common/Data/Mappers/ProductDTOMapper.cs, Restaurante-Back-End/Restaurante.Application/Products/Requests/Delete/DeleteProductRequest.cs, Restaurante-Back-End/Restaurante.Application/Products/Requests/Update/UpdateProductRequest.cs, Restaurante-Back-End/Restaurante.Application/Products/Services/ProductService.cs, Restaurante-Back-End/Restaurante.Infra/InfraConfiguration.cs, Restaurante-Back-End/Restaurante.Infra/Invoices/Repositories/InvoiceRepository.cs, Restaurante-Back-End/Restaurante.Infra/Products/ProductRepository.cs, Restaurante-Back-End/Restaurante.Test/Services/ProductServiceTests.cs, Restaurante-Front-End/src/app/pages/products/create-product/create-product.component.ts, Restaurante-Front-End/src/app/pages/products/edit-product/edit-product.component.html, Restaurante-Front-End/src/app/pages/products/edit-product/edit-product.component.ts, Restaurante-Front-End/src/app/pages/products/edit-product/edit-product.module.ts, Restaurante-Front-End/src/app/pages/products/list-product/list-product.component.html, Restaurante-Front-End/src/app/pages/products/list-product/list-product.component.ts, Restaurante-Front-End/src/app/pages/products/products.routing.ts, Restaurante-Front-End/src/app/pages/products/services/product.service.ts, Restaurante-Front-End/src/app/services/alert.service.ts
Implementando deleção e edição do produto
=> Implementando deleção e edição do produto

Restaurante-Back-End/Restaurante.Application/Products/Requests/Get/SearchProductsRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Deliveries/Services/DeliveryPersonService.cs, Restaurante-Back-End/Restaurante.Application/Users/Employees/Requests/GetAll/GetAllEmployeesRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Employees/Requests/GetAll/SearchEmployeesRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Employees/Services/EmployeeService.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Repositories/Interfaces/IEmployeeDomainRepository.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Services/Interfaces/IEmployeesService.cs, Restaurante-Back-End/Restaurante.Infra/Users/Employees/EmployeesRepository.cs, Restaurante-Back-End/Restaurante.Web/Controllers/EmployeesController.cs
Implementando filtro de funcionarios com paginação.
=> Implementando filtro de funcionarios com paginação.

Restaurante-Back-End/Restaurante.Application/Products/Services/ProductService.cs, Restaurante-Back-End/Restaurante.Domain/Products/Models/Product.cs, Restaurante-Front-End/src/app/components/side-nav/side-nav.component.html, Restaurante-Front-End/src/app/pages/bank/create/create.bank.module.ts, Restaurante-Front-End/src/app/pages/bank/list-bank/list-bank.module.ts, Restaurante-Front-End/src/app/pages/products/list-product/list-product.component.ts
Ajustando atualização do produto.
=> Ajustando atualização do produto.

Restaurante-Back-End/Restaurante.Application/Users/Common/Models/CustomerRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Customers/Requests/CreateCustomerRequest.cs, Restaurante-Back-End/Restaurante.Domain/Users/Customers/Models/Customer.cs, Restaurante-Back-End/Restaurante.Infra/Users/Customers/CustomersRepository.cs, Restaurante-Back-End/Restaurante.Web/Controllers/CustomerController.cs, Restaurante-Back-End/Restaurante.Web/Controllers/InvoiceController.cs, Restaurante-Back-End/Restaurante.Web/Controllers/ProductsController.cs, Restaurante-Back-End/Restaurante.Web/appsettings.json, Restaurante-Front-End/src/environments/environment.dev.ts
Finalizando integração para novos clientes.
=> Finalizando integração para novos clientes.

Restaurante-Back-End/Restaurante.Application/Users/Customers/Requests/CreateCustomerRequest.cs, Restaurante-Back-End/Restaurante.Domain/Users/Customers/Models/Customer.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/DatabaseInitializer.cs, Restaurante-Back-End/Restaurante.Infra/Mappings/CustomerMapping.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211120162432_customer.Designer.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211120162432_customer.cs, Restaurante-Back-End/Restaurante.Infra/Users/Customers/CustomersRepository.cs, Restaurante-Back-End/Restaurante.Web/Controllers/CustomerController.cs
Ajustando integrações entre serviços.
=> Ajustando integrações entre serviços.

Restaurante-Back-End/Restaurante.Application/Common/Response.cs, Restaurante-Back-End/Restaurante.Application/Users/Common/Models/CustomerRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Customers/Requests/CreateCustomerRequest.cs, Restaurante-Back-End/Restaurante.Application/Users/Customers/Requests/GetUserAuthenticateRequest.cs, Restaurante-Back-End/Restaurante.Domain/Users/Customers/Models/Customer.cs, Restaurante-Back-End/Restaurante.Domain/Users/Customers/Models/CustomerPhone.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211121010934_customer-phone.Designer.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211121010934_customer-phone.cs, Restaurante-Back-End/Restaurante.Infra/Users/Customers/CustomersRepository.cs, Restaurante-Back-End/Restaurante.Web/Controllers/CustomerController.cs, Restaurante-Back-End/Restaurante.Web/Startup.cs
Implementando login do cliente.
=> Implementando login do cliente.

Restaurante-Back-End/Restaurante.Domain/Products/Models/ProductCategory.cs, Restaurante-Back-End/Restaurante.Domain/Users/Common/Models/User.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Address.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Employee.cs, Restaurante-Back-End/Restaurante.Domain/Users/Employees/Models/Phone.cs, Restaurante-Back-End/Restaurante.Infra/Common/Persistence/RestauranteDbContext.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211123192734_seeds.Designer.cs, Restaurante-Back-End/Restaurante.Infra/Migrations/20211123192734_seeds.cs, Restaurante-Back-End/Restaurante.Infra/Seeds/Seeds.Employees.cs, Restaurante-Back-End/Restaurante.Infra/Seeds/Seeds.ProductCategories.cs, Restaurante-Back-End/Restaurante.Web/Controllers/ProductsController.cs
Adicionando seeds para categoria de produtos.
=> Adicionando seeds para categoria de produtos.

Restaurante-Back-End/Restaurante.Infra/Products/ProductRepository.cs
Criando endpoint para produtos agrupados por categoria.
=> Criando endpoint para produtos agrupados por categoria.
